//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses.Domain.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Expenses.Domain.Localization.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credit amount must be greater than zero..
        /// </summary>
        internal static string CreditInvalidAmount {
            get {
                return ResourceManager.GetString("CreditInvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No creditor set..
        /// </summary>
        internal static string CreditInvalidCreditor {
            get {
                return ResourceManager.GetString("CreditInvalidCreditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid currency code..
        /// </summary>
        internal static string CurrencyInvalidCode {
            get {
                return ResourceManager.GetString("CurrencyInvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency code must have a length of three, according to ISO..
        /// </summary>
        internal static string CurrencyInvalidLength {
            get {
                return ResourceManager.GetString("CurrencyInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The debit amount must be greater than zero..
        /// </summary>
        internal static string DebitInvalidAmount {
            get {
                return ResourceManager.GetString("DebitInvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No debitor set..
        /// </summary>
        internal static string DebitInvalidDebitor {
            get {
                return ResourceManager.GetString("DebitInvalidDebitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expenese date must be in range of event start and end date..
        /// </summary>
        internal static string EventAddExpenseDateNotInRange {
            get {
                return ResourceManager.GetString("EventAddExpenseDateNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currency does not match the event currency..
        /// </summary>
        internal static string EventAddExpenseInvalidCurrency {
            get {
                return ResourceManager.GetString("EventAddExpenseInvalidCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No credit set..
        /// </summary>
        internal static string EventAddExpenseNoCredit {
            get {
                return ResourceManager.GetString("EventAddExpenseNoCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No debits set..
        /// </summary>
        internal static string EventAddExpenseNoDebits {
            get {
                return ResourceManager.GetString("EventAddExpenseNoDebits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user is not part of the event and cannot be added..
        /// </summary>
        internal static string EventAddExpenseUserNotInEvent {
            get {
                return ResourceManager.GetString("EventAddExpenseUserNotInEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant already exists in event..
        /// </summary>
        internal static string EventAddParticipantExists {
            get {
                return ResourceManager.GetString("EventAddParticipantExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date must be before or same as end date..
        /// </summary>
        internal static string EventInvalidDateRange {
            get {
                return ResourceManager.GetString("EventInvalidDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No creator set..
        /// </summary>
        internal static string EventNoCreator {
            get {
                return ResourceManager.GetString("EventNoCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No currency set..
        /// </summary>
        internal static string EventNoCurrency {
            get {
                return ResourceManager.GetString("EventNoCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description set..
        /// </summary>
        internal static string EventNoDescription {
            get {
                return ResourceManager.GetString("EventNoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No end date set..
        /// </summary>
        internal static string EventNoEndDate {
            get {
                return ResourceManager.GetString("EventNoEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No start date set..
        /// </summary>
        internal static string EventNoStartDate {
            get {
                return ResourceManager.GetString("EventNoStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No title set..
        /// </summary>
        internal static string EventNoTitle {
            get {
                return ResourceManager.GetString("EventNoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expense could not be found..
        /// </summary>
        internal static string EventRemoveExpenseNotFound {
            get {
                return ResourceManager.GetString("EventRemoveExpenseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant takes part in expense and cannot be deleted..
        /// </summary>
        internal static string EventRemoveParticipantHasExpenses {
            get {
                return ResourceManager.GetString("EventRemoveParticipantHasExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant was not found..
        /// </summary>
        internal static string EventRemoveParticipantNotFound {
            get {
                return ResourceManager.GetString("EventRemoveParticipantNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency must have length of three..
        /// </summary>
        internal static string ExpenseInvalidCurrencyLength {
            get {
                return ResourceManager.GetString("ExpenseInvalidCurrencyLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No creator set..
        /// </summary>
        internal static string ExpenseNoCreator {
            get {
                return ResourceManager.GetString("ExpenseNoCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No currency set..
        /// </summary>
        internal static string ExpenseNoCurrency {
            get {
                return ResourceManager.GetString("ExpenseNoCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No date set..
        /// </summary>
        internal static string ExpenseNoDate {
            get {
                return ResourceManager.GetString("ExpenseNoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description set..
        /// </summary>
        internal static string ExpenseNoDescription {
            get {
                return ResourceManager.GetString("ExpenseNoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No title set..
        /// </summary>
        internal static string ExpenseNoTitle {
            get {
                return ResourceManager.GetString("ExpenseNoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A debitor can only take part once..
        /// </summary>
        internal static string ExpenseSplitDebitorDuplication {
            get {
                return ResourceManager.GetString("ExpenseSplitDebitorDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The balance between credit and debits is invalid..
        /// </summary>
        internal static string ExpenseSplitInvalidBalance {
            get {
                return ResourceManager.GetString("ExpenseSplitInvalidBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No credit set..
        /// </summary>
        internal static string ExpenseSplitNoCredit {
            get {
                return ResourceManager.GetString("ExpenseSplitNoCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No debit set..
        /// </summary>
        internal static string ExpenseSplitNoDebits {
            get {
                return ResourceManager.GetString("ExpenseSplitNoDebits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id must not be empty..
        /// </summary>
        internal static string UserInvalidId {
            get {
                return ResourceManager.GetString("UserInvalidId", resourceCulture);
            }
        }
    }
}
