//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses.Application.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Expenses.Application.Localization.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency is required according to ISO 4217..
        /// </summary>
        internal static string EventCreateCurrency {
            get {
                return ResourceManager.GetString("EventCreateCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        internal static string EventCreateDescriptionRequired {
            get {
                return ResourceManager.GetString("EventCreateDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date is required..
        /// </summary>
        internal static string EventCreateEndDate {
            get {
                return ResourceManager.GetString("EventCreateEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date is required..
        /// </summary>
        internal static string EventCreateStartDate {
            get {
                return ResourceManager.GetString("EventCreateStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        internal static string EventCreateTitleRequired {
            get {
                return ResourceManager.GetString("EventCreateTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        internal static string EventUpdateDescriptionRequired {
            get {
                return ResourceManager.GetString("EventUpdateDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        internal static string EventUpdateTitleRequired {
            get {
                return ResourceManager.GetString("EventUpdateTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A creditor amount is required..
        /// </summary>
        internal static string ExpenseCreateCreditorAmountRequired {
            get {
                return ResourceManager.GetString("ExpenseCreateCreditorAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A creditor id is required..
        /// </summary>
        internal static string ExpenseCreateCreditorIdRequired {
            get {
                return ResourceManager.GetString("ExpenseCreateCreditorIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is required..
        /// </summary>
        internal static string ExpenseCreateDateRequired {
            get {
                return ResourceManager.GetString("ExpenseCreateDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A debitor amount is required..
        /// </summary>
        internal static string ExpenseCreateDebitorAmountRequired {
            get {
                return ResourceManager.GetString("ExpenseCreateDebitorAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A debitor id is required..
        /// </summary>
        internal static string ExpenseCreateDebitorIdRequired {
            get {
                return ResourceManager.GetString("ExpenseCreateDebitorIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        internal static string ExpenseCreateDescriptionRequired {
            get {
                return ResourceManager.GetString("ExpenseCreateDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        internal static string ExpenseCreateTitleRequired {
            get {
                return ResourceManager.GetString("ExpenseCreateTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A creditor amount is required..
        /// </summary>
        internal static string ExpenseUpdateCreditorAmountRequired {
            get {
                return ResourceManager.GetString("ExpenseUpdateCreditorAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A creditor id is required..
        /// </summary>
        internal static string ExpenseUpdateCreditorIdRequired {
            get {
                return ResourceManager.GetString("ExpenseUpdateCreditorIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A debitor amount is required..
        /// </summary>
        internal static string ExpenseUpdateDebitorAmountRequired {
            get {
                return ResourceManager.GetString("ExpenseUpdateDebitorAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A debitor id is required..
        /// </summary>
        internal static string ExpenseUpdateDebitorIdRequired {
            get {
                return ResourceManager.GetString("ExpenseUpdateDebitorIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        internal static string ExpenseUpdateDescriptionRequired {
            get {
                return ResourceManager.GetString("ExpenseUpdateDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        internal static string ExpenseUpdateTitleRequired {
            get {
                return ResourceManager.GetString("ExpenseUpdateTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No password set..
        /// </summary>
        internal static string LoginNoPassword {
            get {
                return ResourceManager.GetString("LoginNoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No username set..
        /// </summary>
        internal static string LoginNoUsername {
            get {
                return ResourceManager.GetString("LoginNoUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email..
        /// </summary>
        internal static string RegisterInvalidEmail {
            get {
                return ResourceManager.GetString("RegisterInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password..
        /// </summary>
        internal static string RegisterInvalidPassword {
            get {
                return ResourceManager.GetString("RegisterInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No first name set..
        /// </summary>
        internal static string RegisterNoFirstName {
            get {
                return ResourceManager.GetString("RegisterNoFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No last name set..
        /// </summary>
        internal static string RegisterNoLastName {
            get {
                return ResourceManager.GetString("RegisterNoLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No username set..
        /// </summary>
        internal static string RegisterNoUsername {
            get {
                return ResourceManager.GetString("RegisterNoUsername", resourceCulture);
            }
        }
    }
}
